# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('c0', models.BooleanField(default=False)),
                ('l0', models.TimeField(blank=True, null=True)),
                ('c1', models.BooleanField(default=False)),
                ('l1', models.TimeField(blank=True, null=True)),
                ('c2', models.BooleanField(default=False)),
                ('l2', models.TimeField(blank=True, null=True)),
                ('c3', models.BooleanField(default=False)),
                ('l3', models.TimeField(blank=True, null=True)),
                ('c4', models.BooleanField(default=False)),
                ('l4', models.TimeField(blank=True, null=True)),
                ('c5', models.BooleanField(default=False)),
                ('l5', models.TimeField(blank=True, null=True)),
                ('c6', models.BooleanField(default=False)),
                ('l6', models.TimeField(blank=True, null=True)),
                ('c7', models.BooleanField(default=False)),
                ('l7', models.TimeField(blank=True, null=True)),
                ('c8', models.BooleanField(default=False)),
                ('l8', models.TimeField(blank=True, null=True)),
                ('c9', models.BooleanField(default=False)),
                ('l9', models.TimeField(blank=True, null=True)),
                ('c10', models.BooleanField(default=False)),
                ('l10', models.TimeField(blank=True, null=True)),
                ('c11', models.BooleanField(default=False)),
                ('l11', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('ans', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
