# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fig',
            name='c0',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c10',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c11',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c5',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c6',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c7',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c8',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='c9',
        ),
        migrations.AddField(
            model_name='fig',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
