# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180208_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fig',
            name='l0',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l1',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l10',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l11',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l2',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l3',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l4',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l5',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l6',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l7',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l8',
        ),
        migrations.RemoveField(
            model_name='fig',
            name='l9',
        ),
        migrations.AddField(
            model_name='fig',
            name='timeval',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='ans',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
